<?php
/**
 * Created by PhpStorm.
 * User: ducanhle
 * Date: 8/24/17
 * Time: 11:46 AM
 */

use Application\Controller\FacebookController;
use Application\Controller\IndexController;

$returnLink           = $this->return ? $this->return : $this->url(IndexController::ROUTE_HOME_NAME);
$facebookRegisterLink = $this->url(FacebookController::ROUTE_REGISTER_NAME, [], ['query' => ['return' => $returnLink]]);
?>
<h1>REGISTER PAGE</h1>
<a class="btn btn-primary" href="<?= $facebookRegisterLink ?>">Facebook</a>
