<?php
/**
 * Created by PhpStorm.
 * User: work
 * Date: 13/11/2017
 * Time: 11:53
 */

/** @var \Zend\Form\Form  $form */

$LabelUserName = $form->get('Identity');
$LabelUserName->setAttribute('class', 'label-success');

$mCurrentPassword = $form->get('txtCurrentPassword');
$mCurrentPassword->setAttribute('class', 'form-control');
$mCurrentPassword->setAttribute('Placeholder', 'Password');

$mPassword = $form->get('txtPassword');
$mPassword->setAttribute('class', 'form-control');
$mPassword->setAttribute('Placeholder', 'Password');

$mConfirmPassword = $form->get('txtConfirmPassword');
$mConfirmPassword->setAttribute('class', 'form-control');
$mConfirmPassword->setAttribute('Placeholder', 'Password');

$mResultMessages = $form->get('ResultMessages');
$mResultMessages->setAttribute('class', 'label-warning');

$submit = $form->get('submit');

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <label>User name:</label>
        <label class="label label-warning"><?= $form->get('Identity')->getValue() ?></label>
</div>
<div class="form-group">
    <?= $this->formLabel($mCurrentPassword) ?>
    <?= $this->formElement($mCurrentPassword) ?>
    <?= $this->formElementErrors()->render($mCurrentPassword, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($mPassword) ?>
    <?= $this->formElement($mPassword) ?>
    <?= $this->formElementErrors()->render($mPassword, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($mConfirmPassword) ?>
    <?= $this->formElement($mConfirmPassword) ?>
    <?= $this->formElementErrors()->render($mConfirmPassword, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <label class="label label-warning"><?= $form->get('ResultMessages')->getValue() ?></label>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
?>
