<?php
/**
 * Created by PhpStorm.
 * User: work
 * Date: 10/11/2017
 * Time: 14:49
 */

use CreativeDelta\User\Account\Form\RegisterForm;

/** @var RegisterForm $form */

$mUsername = $form->get(RegisterForm::ELEMENT_TXT_USERNAME);
$mUsername->setAttribute('class', 'form-control');
$mUsername->setAttribute('Placeholder', 'User name');

$mPassword = $form->get(RegisterForm::ELEMENT_TXT_PASSWORD);
$mPassword->setAttribute('class', 'form-control');
$mPassword->setAttribute('Placeholder', 'Password');

$mConfirmPassword = $form->get(RegisterForm::ELEMENT_TXT_CONFIRM_PASSWORD);
$mConfirmPassword->setAttribute('class', 'form-control');
$mConfirmPassword->setAttribute('Placeholder', 'Password');

$mResultMessages = $form->get(RegisterForm::ELEMENT_RESULT_MESSAGES);
$mResultMessages->setAttribute('class', 'label-warning');

echo $this->form()->openTag($form);
?>

    <div class="form-group">
        <?= $this->formLabel($mUsername) ?>
        <?= $this->formElement($mUsername) ?>
        <?= $this->formElementErrors()->render($mUsername, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($mPassword) ?>
        <?= $this->formElement($mPassword) ?>
        <?= $this->formElementErrors()->render($mPassword, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($mConfirmPassword) ?>
        <?= $this->formElement($mConfirmPassword) ?>
        <?= $this->formElementErrors()->render($mConfirmPassword, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <label class="label label-warning"><?= $form->get(RegisterForm::ELEMENT_RESULT_MESSAGES)->getValue() ?></label>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>

<?php
echo $this->form()->closeTag();
?>