<?php
/**
 * Created by PhpStorm.
 * User: work
 * Date: 10/11/2017
 * Time: 11:08
 */

use CreativeDelta\User\Account\Form\SignInForm;

/** @var SignInForm $form */

$mUsername = $form->get(SignInForm::ELEMENT_TXT_USERNAME);
$mUsername->setAttribute('class', 'form-control');
$mUsername->setAttribute('Placeholder', 'Username');

$mPassword = $form->get(SignInForm::ELEMENT_TXT_PASSWORD);
$mPassword->setAttribute('class', 'form-control');
$mPassword->setAttribute('Placeholder', 'Password');

$mResultMessages = $form->get(SignInForm::ELEMENT_RESULT_MESSAGES);
$mResultMessages->setAttribute('class', 'label-warning');

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($mUsername) ?>
        <?= $this->formElement($mUsername) ?>
        <?= $this->formElementErrors()->render($mUsername, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($mPassword) ?>
        <?= $this->formElement($mPassword) ?>
        <?= $this->formElementErrors()->render($mPassword, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <label class="label label-warning"><?= $form->get(SignInForm::ELEMENT_RESULT_MESSAGES)->getValue() ?></label>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
<?php
echo $this->form()->closeTag();
?>