<?php
/**
 * Created by PhpStorm.
 * User: ducanhle
 * Date: 8/24/17
 * Time: 3:33 PM
 */

use CreativeDelta\User\Application\Controller\IndexController;
use CreativeDelta\User\Core\Domain\Entity\Identity;

/** @var Identity $identity */
$identity = $this->identity();
$homeLink = $this->url(IndexController::ROUTE_HOME_NAME);
?>
<h1>Secured Page</h1>
<h3>Identity: <?= $identity->getAccount() ?></h3>
<a class="btn btn-default" href="<?= $homeLink ?>">Back to home</a>
